name: 버그 레포트
description: 문제 상황과 관련된 버그를 보고하는데 사용합니다.
title: "bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## Issue Title\n<!-- 간결하게 문제 상황을 나타내는 제목을 작성하세요. -->"

  - type: textarea
    attributes:
      label: "문제 상황"
      description: "어떤 문제가 발생했는지 구체적으로 기술하세요. 가능하다면, 문제가 언제, 어떻게 발생하는지를 포함한 상황을 자세히 설명하세요."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "기대하는 동작"
      description: "문제 상황이 발생하지 않았을 때 어떤 동작을 기대했는지 설명하세요."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "추가 정보"
      description: "문제 상황과 관련하여 추가적인 정보가 있다면 기입하세요."
