---
spring:
    config:
        activate:
            on-profile: test
        import:
            - classpath:/application-domain.yaml

jwt:
    secret-key: secretKeyForTestsecretKeyForTestsecretKeyForTestsecretKeyForTest
